# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _icom
else:
    import _icom

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


ICOM_BLOCK = _icom.ICOM_BLOCK
ICOM_NONBLOCK = _icom.ICOM_NONBLOCK

def get_version():
    return _icom.get_version()
class server(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, port, length_header, length_chunk):
        _icom.server_swiginit(self, _icom.new_server(port, length_header, length_chunk))

    def start(self):
        return _icom.server_start(self)

    def server_thread(self):
        return _icom.server_server_thread(self)

    def send(self, s):
        return _icom.server_send(self, s)

    def recv(self, data, length_data):
        return _icom.server_recv(self, data, length_data)

    def recv_nonblock(self, data, length_data):
        return _icom.server_recv_nonblock(self, data, length_data)

    def wait_for_connection(self):
        return _icom.server_wait_for_connection(self)

    def close(self):
        return _icom.server_close(self)

    def is_connected(self):
        return _icom.server_is_connected(self)
    __swig_destroy__ = _icom.delete_server

# Register server in _icom:
_icom.server_swigregister(server)
class client(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, ip, port, length_header, length_chunk):
        _icom.client_swiginit(self, _icom.new_client(ip, port, length_header, length_chunk))

    def connect(self):
        return _icom.client_connect(self)

    def send(self, s):
        return _icom.client_send(self, s)

    def recv(self, data, length_data):
        return _icom.client_recv(self, data, length_data)

    def recv_nonblock(self, data, length_data):
        return _icom.client_recv_nonblock(self, data, length_data)

    def close(self):
        return _icom.client_close(self)

    def is_connected(self):
        return _icom.client_is_connected(self)
    __swig_destroy__ = _icom.delete_client

# Register client in _icom:
_icom.client_swigregister(client)

